all: deploy

deploy: MiniCVNative.so
	cp MiniCVNative.so ../../lib/Native/MiniCV/linux/AMD64/MiniCVNative.so

MiniCVNative.o: MiniCVNative.cpp MiniCVNative.h
	g++ -std=c++11 -fPIC -c MiniCVNative.cpp -I../../include -o MiniCVNative.o

fivepoint.o: fivepoint.cpp fivepoint.h
	g++ -std=c++11 -fPIC -c fivepoint.cpp -I../../include -o fivepoint.o

ap3p.o: ap3p.cpp ap3p.h
	g++ -std=c++11 -fPIC -c ap3p.cpp -I../../include -o ap3p.o

MiniCVNative.so: MiniCVNative.o fivepoint.o ap3p.o
	g++ MiniCVNative.o fivepoint.o ap3p.o -shared -o MiniCVNative.so ../../lib/Native/MiniCV/linux/AMD64/libopencv_features2d.so.3.2.0 ../../lib/Native/MiniCV/linux/AMD64/libopencv_core.so.3.2.0 ../../lib/Native/MiniCV/linux/AMD64/libopencv_calib3d.so.3.2.0 ../../lib/Native/MiniCV/linux/AMD64/libopencv_imgproc.so.3.2.0 ../../lib/Native/MiniCV/linux/AMD64/libopencv_imgcodecs.so.3.2.0

.PHONY clean:
	rm -fr *.o MiniCVNative.so
